FROM node:22-alpine3.19

WORKDIR /app
COPY package.json ./
COPY .npmrc ./
COPY tsconfig.json ./
COPY src ./src
COPY tools ./tools

RUN ls -a 
RUN npm install && npm install -g nodemon

EXPOSE 4004

CMD [ "npm","run","dev" ]